version: "3.3"
services:
  dialer:
    build: api-dialer/
    image: api-dialer:1.1
    ports:
      - "8081:8081"
    environment:
      - SERVER_PORT=8081
      - SERVER_SERVLET_CONTEXT_PATH=/api
      - NGROK_DOMAIN=https://26e2-38-25-17-223.ngrok.io
      - APP_HOOK_URL=https://26e2-38-25-17-223.ngrok.io/dialer/api/v1/call/hook
      - RING_CENTRAL_SUBSCRIPTION_TTL=86400
      - RING_CENTRAL_URL=https://platform.devtest.ringcentral.com
      - RING_CENTRAL_MAIN_ACCOUNT_CLIENT_ID=d6MzVZUCTOiFnWBXn1C00w
      - RING_CENTRAL_MAIN_ACCOUNT_CLIENT_SECRET=<>
      - RING_CENTRAL_MAIN_ACCOUNT_USERNAME=+12054849099
      - RING_CENTRAL_MAIN_ACCOUNT_PASSWORD=<>
      - RING_CENTRAL_MAIN_ACCOUNT_EXTENSION=101
  app:
    build: front-end/
    image: app:1.1
    ports:
      - "8080:8080"