server:
  port: 8081
  servlet:
    context-path: /api

spring:
  jpa:
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_schema: dialer
        dialect: org.hibernate.dialect.PostgreSQLDialect
  datasource:
    url: jdbc:postgresql://localhost:5433/postgres?stringtype=unspecified
    username: postgres
    password: postgres
    
app:
  hook-url: ${NGROK_DOMAIN}/dialer/api/v1/call/hook
  ring-central:
    subscription-ttl: 86400
    url: https://platform.devtest.ringcentral.com
    main-account:
      client-id: d6MzVZUCTOiFnWBXn1C00w
      client-secret: aeMt49DdQ221Kh3dRYyHpwZ4R-EGJOSWKIESAcStujNg
      username: ~
      password: china@123
      extension: ~